# Generated by Django 5.0.1 on 2024-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(max_length=100)),
                ('RFC', models.CharField(max_length=13)),
                ('CodigoPostal', models.CharField(max_length=5)),
                ('TipoPersona', models.PositiveSmallIntegerField(choices=[(1, 'PERSONA FÍSICA'), (2, 'PERSONA MORAL')], default=1)),
                ('RegimenFiscal', models.PositiveSmallIntegerField(choices=[(1, 'PERSONA FÍSICA'), (2, 'PERSONA MORAL')], default=1)),
                ('ContraseñaFirma', models.CharField(max_length=100)),
                ('ContraseñaImss', models.CharField(max_length=100)),
                ('ContraseñaInfonavit', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
