# Generated by Django 5.0.1 on 2024-07-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo4',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='archivo5',
        ),
    ]
