# Generated by Django 5.0.1 on 2024-08-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_documento_archivo4_remove_documento_archivo5'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyentes',
            name='correo_electronico',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
